### PR TITLE
Luci

### PR DESCRIPTION
**Pull request by lucitemple**
Code for the Appointments part of the project - steps 7-9. 

One thing not working yet: the select/option ContactPicker.

### CODE REVIEW

**Review by Amutha37 — CHANGES_REQUESTED** [review]
Luci can you change the key={contact.contact} in contact picker.

**Comment by lucitemple** [comment]
> Luci can you change the key={contact.contact} in contact picker.

@Amutha37 What is the logic behind the change requested?

The ContactPicker component uses the information stored in App.js state defined contacts array, where the the contact data has been stored as an object with `contactName`, `phone` and `email` as the keys via the `addContact()` method.

**Review by Amutha37 — CHANGES_REQUESTED** [review]
We can use contact phone number for the key. It's unique to individual .

**Review by Amutha37 — APPROVED** [review]
Approved we can you the new change.

**Pull request merged**
